name: Audi RED Data Collection

on:
    workflow_call:
        inputs:
            jest_artifact_path:
                description: 'jest artifact name when uploaded'
                required: false
                type: string
            lighthouse_artifact_path:
                description: 'lighthouse artifact name when uploaded'
                required: false
                type: string

jobs:
    audired_collection:
        runs-on: ubuntu-latest
        steps:
            - name: Check Jest coverage percentage
              if: ${{ inputs.jest_artifact_path }}
              run: |
                LINES=$(jq '.total.lines.pct' < ${{ inputs.jest_artifact_path }})
                STATEMENTS=$(jq '.total.statements.pct' < ${{ inputs.jest_artifact_path }})
                FUNCTIONS=$(jq '.total.functions.pct' < ${{ inputs.jest_artifact_path }})
                BRANCHES=$(jq '.total.branches.pct' < ${{ inputs.jest_artifact_path }})
        
                echo "Line coverage: $LINES%"
                echo "Statement coverage: $STATEMENTS%"
                echo "Function coverage: $FUNCTIONS%"
                echo "Branch coverage: $BRANCHES%"
        
                AVERAGE_COVERAGE=$(echo "($LINES + $STATEMENTS + $FUNCTIONS + $BRANCHES) / 4" | bc -l)
        
                echo "Average coverage: $AVERAGE_COVERAGE%"
        
                # Fail the job if the average coverage is below 80%
                if (( $(echo "$AVERAGE_COVERAGE > 80" | bc -l) )); then
                    echo "Wahoo! Average jest test coverage is above 80%. Assigning gold badge"
                elif (( $(echo "$AVERAGE_COVERAGE > 60" | bc -l) )); then
                    echo "Good job! Results actual is above 60%. Assigning silver badge"
                else
                    echo "Results actual needs to be higher. Assigning bronze badge."
                fi
            
            - name: Check lighthouse coverage percentage
              if: ${{ inputs.lighthouse_artifact_path }}
              run: |
                # Extract the coverage percentages for lines, statements, functions, and branches
                RESULTS_ACTUAL=$(jq '.[0].actual' < ${{inputs.lighthouse_artifact_path}})

                if [ -z  "$RESULTS_ACTUAL" ]; then
                    echo "No lighthouse data available"
                else
                    echo "Results actual found: $RESULTS_ACTUAL%"
                    if (( $(echo "$RESULTS_ACTUAL > 80" | bc -l) )); then
                        echo "Results actual is above 80%. Assigning gold badge"
                    elif (( $(echo "$RESULTS_ACTUAL > 60" | bc -l) )); then
                        echo "Results actual is above 60%. Assigning silver badge"
                    else
                        echo "Results actual needs to be higher. Assigning bronze badge."
                    fi
                fi
